image: microsoft/dotnet/core/sdk:3.1

stages:
    - build
    - test

before_script:
    - "cd src"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script: 
        - "cd .."
        - "dotnet test"