version: '3'
services: 
    inventory:
        build: ../Inventory/WebApi
        container_name: inventory
        ports:
            - 7000:80
            - 7001:443
    places:
        build: ../Places/WebApi/Places.WebApi
        container_name: places
        ports:
            - 7300:80
            - 7301:443
            