version: "3.7"
services: 
    db:
        image: mcr.microsoft.com/mssql/server
        environment:
            SA_PASSWORD: "ZAQ!2wsx"
            ACCEPT_EULA: "Y"
        ports:
            - 1433:1433    

    rabbitmq:
        image: rabbitmq:3.8-management
        hostname: rabbitmq
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./data/rabbitmq:/var/lib/rabbitmq
            - ./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins
